#!/usr/bin/env bash

#if [ -d "$HOME/.config/dotfiles" ]; then
#    echo "Dotfiles directory exists."
#else
#    echo "Creating dotfiles directory."
#    sudo git clone git@github.com:CatalinVoineag/dotfiles.git $HOME/.config/dotfiles
#fi
