#!/usr/bin/env bash

sudo pacman -S --noconfirm --needed nautilus
sudo pacman -S --noconfirm --needed git
sudo pacman -S --noconfirm --needed fzf
sudo pacman -S --noconfirm --needed yay
sudo pacman -S --noconfirm --needed piper
sudo pacman -S --noconfirm --needed pavucontrol
sudo pacman -S --noconfirm --needed vlc ffmpeg gst-libav gst-plugins-good gst-plugins-bad gst-plugins-ugly
sudo pacman -S --noconfirm --needed vlc-plugins-all
sudo pacman -S --noconfirm --needed jq
sudo pacman -S --noconfirm --needed xclip
sudo pacman -S --noconfirm --needed less
sudo pacman -S --noconfirm --needed ttf-jetbrains-mono-nerd ttf-font-awesome otf-font-awesome
sudo pacman -S --noconfirm --needed base-devel libffi zlib openssl readline curl
sudo pacman -S --noconfirm --needed yaml libyaml
sudo pacman -S --noconfirm --needed obsidian
sudo pacman -S --noconfirm --needed discord
yay -S --noconfirm --needed slack-desktop

go install github.com/CatalinVoineag/fundal@latest

if [ -d "$HOME/knowledge_grave" ]; then
  echo "knowledge_grave exists"
else
  git clone git@github.com:CatalinVoineag/knowledge_grave.git $HOME/knowledge_grave
fi
