#!/usr/bin/env bash

sudo pacman -S --noconfirm --needed nautilus
sudo pacman -S --noconfirm --needed git
sudo pacman -S --noconfirm --needed fzf
sudo pacman -S --noconfirm --needed piper
sudo pacman -S --noconfirm --needed pavucontrol
sudo pacman -S --noconfirm --needed vlc ffmpeg gst-libav gst-plugins-good gst-plugins-bad gst-plugins-ugly
sudo pacman -S --noconfirm --needed vlc-plugins-all
sudo pacman -S --noconfirm --needed jq
sudo pacman -S --noconfirm --needed wl-clipboard
sudo pacman -S --noconfirm --needed less
sudo pacman -S --noconfirm --needed ttf-jetbrains-mono-nerd ttf-font-awesome otf-font-awesome
sudo pacman -S --noconfirm --needed base-devel libffi zlib openssl readline curl
sudo pacman -S --noconfirm --needed yaml libyaml
sudo pacman -S --noconfirm --needed obsidian
sudo pacman -S --noconfirm --needed discord
sudo pacman -S --noconfirm --needed base-devel openssl zlib binutils libssl zlib-devel libxml2 libxslt
sudo pacman -S --noconfirm --needed tar gzip diffutils 
sudo pacman -S --noconfirm --needed ghostty

if command -v yay &> /dev/null; then
  echo "yay installed"
else
  git clone https://aur.archlinux.org/yay-bin.git $HOME/yay-bin && cd $HOME/yay-bin && makepkg -si 
fi

yay -S --noconfirm --needed slack-desktop signal-desktop

go install github.com/CatalinVoineag/fundal@latest

if [ -d "$HOME/knowledge_grave" ]; then
  echo "knowledge_grave exists"
else
  git clone git@github.com:CatalinVoineag/knowledge_grave.git $HOME/knowledge_grave
fi
