#!/usr/bin/env bash

sudo pacman -S --noconfirm --needed nfs-utils

sudo systemctl enable --now nfs-client.target

if [ -d "/mnt/NFS" ]; then
  echo "/mnt/NFS exists"
else
  sudo mkdir -p /mnt/NFS
fi

if ! grep -q "pi.local:/export/Home /mnt/NFS" /etc/fstab; then
  echo "pi.local:/export/Home /mnt/NFS nfs defaults,noauto,users 0 0" | sudo tee -a /etc/fstab
fi
