#!/usr/bin/env bash

sudo pacman -S --noconfirm --needed nfs-utils

sudo systemctl enable --now nfs-client.target

if [ -d "/mnt/NFS" ]; then
  echo "/mnt/NFS exists"
else
  sudo mkdir -p /mnt/NFS
fi
