#!/usr/bin/env bash

sudo pacman -S --noconfirm --needed neovim
sudo pacman -S --noconfirm --needed lua luarocks lua51-filesystem
sudo pacman -S --noconfirm --needed ccls
sudo pacman -S --noconfirm --needed cargo
sudo pacman -S --noconfirm --needed npm
