#!/usr/bin/env bash

sudo pacman -S --noconfirm --needed flameshot grim
sudo pacman -S --noconfirm --needed obs-studio gst-plugins-good gst-plugins-bad gst-plugins-ugly gst-libav pipewire pipewire-pulse


if [ -d "$HOME/.config/flameshot" ]; then
  echo "flameshot directory exists"
else
  sudo mkdir $HOME/.config/flameshot/
fi
